blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/Make-Lemonade/lemonsqueezy-wp/discussions
    about: Please ask and answer questions here.
  - name: Feature Requests
    url: https://github.com/Make-Lemonade/lemonsqueezy-wp/discussions/categories/ideas
    about: Suggest new features here.
